# Generated by Django 3.2.4 on 2021-06-24 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('subject_uz', models.CharField(max_length=150, verbose_name='Matn sarlavhasi')),
                ('subject_ru', models.CharField(max_length=150, verbose_name='Заголовок текста')),
            ],
            options={
                'verbose_name': 'Afzallik',
                'verbose_name_plural': 'Afzalliklari',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Darsni nomi')),
            ],
        ),
        migrations.CreateModel(
            name='LessonAdvertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_uz', models.CharField(max_length=150, verbose_name='Dars nomi')),
                ('subject_ru', models.CharField(max_length=150, verbose_name='Название курса')),
                ('content_uz', models.CharField(max_length=150, verbose_name='Dars mavzusi')),
                ('content_ru', models.CharField(max_length=150, verbose_name='Тема курса')),
                ('video', models.FileField(upload_to='video/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('subject_uz', models.TextField()),
                ('subject_ru', models.TextField()),
                ('name_uz', models.TextField()),
                ('name_ru', models.TextField()),
                ('button', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_uz', models.CharField(max_length=150, verbose_name='Dars mavzusi')),
                ('subject_ru', models.CharField(max_length=150, verbose_name='Тема курса')),
                ('content_uz', models.CharField(max_length=150, verbose_name='Dars haqida malumotlar')),
                ('content_ru', models.CharField(max_length=150, verbose_name='Информация о курсе')),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_uz', models.CharField(max_length=150, verbose_name='Darsnomi')),
                ('subject_ru', models.CharField(max_length=150, verbose_name='Название курса')),
                ('name_uz', models.CharField(max_length=150)),
                ('name_ru', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'DarsReklama',
                'verbose_name_plural': 'DarsReklamalar',
            },
        ),
        migrations.CreateModel(
            name='VidoTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_uz', models.CharField(max_length=200)),
                ('subject_ru', models.CharField(max_length=200)),
                ('conten_uz', models.TextField()),
                ('conten_ru', models.TextField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('video', models.FileField(upload_to='video/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'Video darsi',
                'verbose_name_plural': 'Video darsilar',
            },
        ),
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('conten_uz', models.TextField()),
                ('conten_ru', models.TextField()),
                ('vidotitle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.vidotitle')),
            ],
        ),
    ]
