# Generated by Django 3.2.4 on 2021-06-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210625_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='video',
            name='price',
        ),
    ]
